### ISSUE TITLE
Can't access Job Center*

### ISSUE THREAD

**Issue by Dmitchell94** [Pepnsi/DefconRP-Bugs#19]
**Can't access Job Center**
I am attempting to access the job center for the first time and despite using lb on my controller as told i can not access it and get a error stating I cant use a weapon in a safe area, tried switching to my keyboard and used e and still the menu would not open despite others being able to access the menu. checking F8 I am seeing a massive spamming of "script:es_extended Invalid ref call Attempt: #######" the number changed each time but it is moving extremly fast and constantly changing

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to job center
2. Access the menu

**Expected behavior**
I would expect to be able to access the job center center and get a job

**Screenshots**
![Screenshot_2](https://user-images.githubusercontent.com/1408174/107911826-4cefe880-6f2b-11eb-86eb-f80fc272c823.png)
![Screenshot_1](https://user-images.githubusercontent.com/1408174/107911828-4d887f00-6f2b-11eb-9304-cd3c6b69fb81.png)

**Additional context**
Sadly I have a feeling this is fairly unique as ive seen other players join and access the menu fine

**Comment by Pepnsi** [comment]
This is a error when a user joins from another ESX server. Just restart your FiveM and you'll be fine!

**Comment by Dmitchell94** [comment]
Thank you was unaware of this issue with esx
